services:
  api:
    image: tb_waiter:local
    container_name: tb_waiter
    build: .
    volumes:
      - /mnt:/mnt:ro
    networks:
      - api_network
    environment:
      - HOSTNAME=${HOSTNAME}
      - API_TOKEN=${API_TOKEN}
      - BOARD_TTL=${BOARD_TTL}
  reverse-proxy:
    image: nginx:alpine
    container_name: reverse-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certs/server.crt:/etc/nginx/certs/server.crt:ro
      - ./certs/server.key:/etc/nginx/certs/server.key:ro

    networks:
      - api_network
    depends_on:
      - api

networks:
  api_network:
    driver: bridge